services:
  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ./ollama:/root/.ollama
    restart: always

  webui:
    image: ghcr.io/open-webui/open-webui
    volumes:
      - ./webui:/app/backend/data
    ports:
      - 8080:8080
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      WEBUI_SECRET_KEY: ""
    restart: always
